### ISSUE TITLE
前端打包失败

### ISSUE THREAD

**Issue by xgy560501** [LianGee/galio-fe#1]
先执行了install下载组件，然后npm start 启动报错，这个如何解决啊

Starting the development server...
Cannot find module 'vs/editor/standalone/browser/quickOpen/gotoLine'
Require stack:
- C:\Users\20111228\Desktop\galio-fe\node_modules\monaco-editor-webpack-plugin\out\index.js
- C:\Users\20111228\Desktop\galio-fe\config\plugin.config.ts
- C:\Users\20111228\Desktop\galio-fe\config\config.ts
- C:\Users\20111228\Desktop\galio-fe\node_modules\@umijs\core\lib\Config\Config.js
- C:\Users\20111228\Desktop\galio-fe\node_modules\@umijs\core\lib\index.js
- C:\Users\20111228\Desktop\galio-fe\node_modules\umi\lib\ServiceWithBuiltIn.js
- C:\Users\20111228\Desktop\galio-fe\node_modules\umi\lib\forkedDev.js
Error: Cannot find module 'vs/editor/standalone/browser/quickOpen/gotoLine'

**Comment by LianGee** [comment]
> 先执行了install下载组件，然后npm start 启动报错，这个如何解决啊
> 
> Starting the development server...
> Cannot find module 'vs/editor/standalone/browser/quickOpen/gotoLine'
> Require stack:
> 
> * C:\Users\20111228\Desktop\galio-fe\node_modules\monaco-editor-webpack-plugin\out\index.js
> * C:\Users\20111228\Desktop\galio-fe\config\plugin.config.ts
> * C:\Users\20111228\Desktop\galio-fe\config\config.ts
> * C:\Users\20111228\Desktop\galio-fe\node_modules@umijs\core\lib\Config\Config.js
> * C:\Users\20111228\Desktop\galio-fe\node_modules@umijs\core\lib\index.js
> * C:\Users\20111228\Desktop\galio-fe\node_modules\umi\lib\ServiceWithBuiltIn.js
> * C:\Users\20111228\Desktop\galio-fe\node_modules\umi\lib\forkedDev.js
>   Error: Cannot find module 'vs/editor/standalone/browser/quickOpen/gotoLine'

组件没安装上吧
